# Generated by Django 5.0.6 on 2024-06-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('etage', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qualite_air', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='chambre',
            constraint=models.UniqueConstraint(fields=('numero', 'etage'), name='unique_chambre'),
        ),
        migrations.AddField(
            model_name='patient',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chambre'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom'), name='unique'),
        ),
    ]
