# Generated by Django 5.0.4 on 2024-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('etage', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qualite_air', models.CharField(max_length=100)),
            ],
        ),
    ]
