# Generated by Django 5.0.4 on 2024-05-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='chambre',
            constraint=models.UniqueConstraint(fields=('numero', 'etage'), name='unique_chambre'),
        ),
    ]
