# Generated by Django 5.0.6 on 2024-06-10 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='date_pointage',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
