# Generated by Django 5.0.4 on 2024-06-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='chambre',
        ),
    ]
