# Generated by Django 5.0.4 on 2024-06-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_patient_chambre'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chambre',
            field=models.IntegerField(default=1),
        ),
    ]
