# Generated by Django 5.0.4 on 2024-06-07 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_patient_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='date_pointage',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='id',
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_personne',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_pointage', models.DateTimeField(blank=True, null=True)),
                ('id_personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personnel')),
            ],
        ),
    ]
