# Generated by Django 5.0.4 on 2024-06-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_patient_date_sortie_alter_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique',
        ),
    ]
