# Generated by Django 5.0.4 on 2024-06-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_personnel_date_pointage_remove_personnel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointage',
            old_name='id_personne',
            new_name='personnel',
        ),
    ]
