# Generated by Django 5.0.4 on 2024-06-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_patient_chambre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='humidite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='qualite_air',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chambre'),
        ),
    ]
